"""Add apartment_id column to Booking table

Revision ID: e3e1c7f353b1
Revises: 
Create Date: 2024-03-31 18:05:34.284724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3e1c7f353b1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('apartment_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'booking', 'apartment', ['apartment_id'], ['id'])
    op.drop_column('booking', 'apartment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('apartment', sa.VARCHAR(length=100), nullable=False))
    op.drop_constraint(None, 'booking', type_='foreignkey')
    op.drop_column('booking', 'apartment_id')
    # ### end Alembic commands ###
